// tls_server.h - an in-process TLS server for the upgrade test.
//
// test_ssl.cpp drives `openssl s_server` as a subprocess, which is the right
// tool when the server should be TLS from the first byte. It cannot be used
// here: s_server has no -starttls option (that is s_client only), so it cannot
// speak a plaintext greeting and then upgrade. This does that directly.
//
// The exchange is deliberately SMTP-shaped, because STARTTLS is the reason the
// primitive under test exists:
//
//     S: 220 test ready              <- plaintext
//     C: STARTTLS
//     S: 220 go ahead                <- plaintext, last thing before the handshake
//     [TLS handshake on the same descriptor]
//     C: PING                        <- encrypted
//     S: PONG                        <- encrypted
//
// Certificate and key are read from cert.pem / key.pem in the working
// directory, generated by the caller with the openssl CLI the same way
// test_ssl.cpp does.
#ifndef RUDESOCKET_TESTS_TLS_SERVER_H
#define RUDESOCKET_TESTS_TLS_SERVER_H

#include "net_util.h"

#include <openssl/err.h>
#include <openssl/ssl.h>

#include <cstdio>
#include <cstring>
#include <string>

class StartTlsServer
{
	net_socket_t d_listen;
	int d_port;

	// Set by the server thread, read by the test after it joins.
	bool d_handshook;

	// When the test is deliberately provoking a rejected handshake, the
	// server's complaint about it is expected output, not a diagnostic.
	// Silencing it keeps a genuine failure visible.
	//
	bool d_quiet;
	std::string d_plaintextLine;
	std::string d_encryptedLine;

	// Reads one CRLF- or LF-terminated line from a plain descriptor.
	static std::string readLinePlain(net_socket_t s)
	{
		std::string out;
		for(;;)
		{
			char c;
			int rc = (int) ::recv(s, &c, 1, 0);
			if(rc <= 0)
				break;
			if(c == '\n')
				break;
			if(c != '\r')
				out += c;
		}
		return out;
	}

	static std::string readLineSsl(SSL *ssl)
	{
		std::string out;
		for(;;)
		{
			char c;
			int rc = SSL_read(ssl, &c, 1);
			if(rc <= 0)
				break;
			if(c == '\n')
				break;
			if(c != '\r')
				out += c;
		}
		return out;
	}

  public:
	StartTlsServer()
		: d_listen(NET_INVALID_SOCKET), d_port(0), d_handshook(false), d_quiet(false)
	{
		d_listen = ::socket(AF_INET, SOCK_STREAM, 0);
		sockaddr_in addr;
		std::memset(&addr, 0, sizeof(addr));
		addr.sin_family = AF_INET;
		addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
		addr.sin_port = 0; // ephemeral
		::bind(d_listen, (sockaddr *) &addr, sizeof(addr));
		::listen(d_listen, 1);
		socklen_t len = sizeof(addr);
		::getsockname(d_listen, (sockaddr *) &addr, &len);
		d_port = ntohs(addr.sin_port);
	}

	~StartTlsServer()
	{
		if(d_listen != NET_INVALID_SOCKET)
			net_close(d_listen);
	}

	int port() const
	{
		return d_port;
	}

	// Call before run() when a failed handshake is the expected outcome.
	void expectHandshakeFailure()
	{
		d_quiet = true;
	}

	// True if the TLS handshake completed.
	bool handshook() const
	{
		return d_handshook;
	}

	// What the client sent before the upgrade, and after it.
	const std::string &plaintextLine() const
	{
		return d_plaintextLine;
	}
	const std::string &encryptedLine() const
	{
		return d_encryptedLine;
	}

	// Accept one client, greet, upgrade on request, then answer once.
	void run()
	{
		net_socket_t c = ::accept(d_listen, 0, 0);
		if(c == NET_INVALID_SOCKET)
			return;

		const char *greeting = "220 test ready\r\n";
		::send(c, greeting, (int) std::strlen(greeting), 0);

		// Whatever the client asks for, in the clear.
		d_plaintextLine = readLinePlain(c);

		const char *go = "220 go ahead\r\n";
		::send(c, go, (int) std::strlen(go), 0);

		// Same descriptor, now wrapped in TLS.
		SSL_CTX *ctx = SSL_CTX_new(TLS_server_method());
		if(!ctx)
		{
			net_close(c);
			return;
		}
		if(SSL_CTX_use_certificate_file(ctx, "cert.pem", SSL_FILETYPE_PEM) <= 0 ||
		   SSL_CTX_use_PrivateKey_file(ctx, "key.pem", SSL_FILETYPE_PEM) <= 0)
		{
			std::fprintf(stderr, "server: could not load cert.pem/key.pem\n");
			SSL_CTX_free(ctx);
			net_close(c);
			return;
		}

		SSL *ssl = SSL_new(ctx);
		SSL_set_fd(ssl, (int) c);
		if(SSL_accept(ssl) == 1)
		{
			d_handshook = true;
			d_encryptedLine = readLineSsl(ssl);
			const char *pong = "PONG\r\n";
			SSL_write(ssl, pong, (int) std::strlen(pong));
			SSL_shutdown(ssl);
		}
		else if(!d_quiet)
		{
			std::fprintf(stderr, "server: SSL_accept failed\n");
			ERR_print_errors_fp(stderr);
		}

		SSL_free(ssl);
		SSL_CTX_free(ctx);
		net_close(c);
	}
};

#endif
